# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

env:
  SNAPSHOTS_SERVICE_URL: https://vt-dev-io.eu-1.24h.sh
  SNAPSHOTS_TOKEN: bud_vt_us_umgclb80y2r8myeo0gl7gkqm40dj12

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: pnpm/action-setup@v2
      with:
        version: 9.6.0
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: 'pnpm'
    - run: sudo apt-get update && sudo apt-get install -y software-properties-common
    - run: sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv eb39332e766364ca6220e8dc631c5a16310cc0ad
    - run: sudo add-apt-repository 'deb [arch=amd64] https://es.buddy.works/bdy/apt-repo dev main'
    - run: sudo apt-get update && sudo apt-get install -y bdy
    - run: pnpm install
    - run: npm run test-ci
